import { Listing } from "@/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    landlord_id: "u1",
    city: "da-nang",
    source: "landlord",
    title: "Phòng trọ cao cấp gần ĐH Duy Tân, full nội thất",
    description:
      "Phòng trọ mới xây, sạch sẽ thoáng mát, đầy đủ nội thất. Gần ĐH Duy Tân 300m, ĐH Đà Nẵng 500m. An ninh 24/7, camera an ninh toàn tòa.",
    address: "120 Nguyễn Lương Bằng, Liên Chiểu",
    district: "Liên Chiểu",
    lat: 16.074,
    lng: 108.149,
    price: 2500000,
    area: 25,
    room_type: "phong_tro",
    max_occupants: 2,
    gender_preference: "all",
    amenities: {
      wifi: true,
      ac: true,
      washer: true,
      parking: true,
      security: true,
      elevator: false,
      kitchen: true,
      balcony: false,
      pet: false,
    },
    status: "active",
    contact_phone: "0905123456",
    view_count: 128,
    contact_count: 14,
    created_at: "2026-05-20T08:00:00Z",
    images: [
      { id: "i1", listing_id: "1", url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", order: 0 },
      { id: "i2", listing_id: "1", url: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80", order: 1 },
      { id: "i3", listing_id: "1", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80", order: 2 },
    ],
    landlord: {
      user_id: "u1",
      full_name: "Nguyễn Văn An",
      avatar_url: null,
      phone: "0905123456",
      verified_phone: true,
      verified_id: true,
    },
  },
  {
    id: "2",
    landlord_id: "u2",
    city: "da-nang",
    source: "admin",
    source_note: "Lấy từ group FB Thuê trọ Đà Nẵng, đã liên hệ xác nhận SĐT",
    source_url: "https://facebook.com/groups/thuetrodanang",
    title: "Căn hộ mini studio trung tâm Hải Châu, ban công view biển",
    description:
      "Studio thiết kế hiện đại, ban công thoáng, view biển Mỹ Khê. Cách biển 5 phút đi bộ. Thích hợp cặp đôi hoặc đi làm.",
    address: "45 Trần Phú, Hải Châu",
    district: "Hải Châu",
    lat: 16.068,
    lng: 108.223,
    price: 4500000,
    area: 35,
    room_type: "chung_cu",
    max_occupants: 2,
    gender_preference: "all",
    amenities: {
      wifi: true,
      ac: true,
      washer: true,
      parking: true,
      security: true,
      elevator: true,
      kitchen: true,
      balcony: true,
      pet: false,
    },
    status: "active",
    contact_phone: "0909876543",
    view_count: 256,
    contact_count: 32,
    created_at: "2026-05-18T10:00:00Z",
    images: [
      { id: "i4", listing_id: "2", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", order: 0 },
      { id: "i5", listing_id: "2", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", order: 1 },
    ],
    landlord: {
      user_id: "u2",
      full_name: "Trần Thị Bích",
      avatar_url: null,
      phone: "0909876543",
      verified_phone: true,
      verified_id: false,
    },
  },
  {
    id: "3",
    landlord_id: "u3",
    city: "da-nang",
    source: "claimed",
    source_note: "Admin đăng từ khảo sát thực địa tháng 5/2026, chủ nhà đã nhận tin",
    title: "Phòng trọ giá rẻ khu sinh viên Thanh Khê",
    description:
      "Phòng trọ giá bình dân, phù hợp sinh viên. Gần chợ Thanh Khê, tiện mua sắm. Wifi miễn phí, điện nước giá nhà nước.",
    address: "78 Điện Biên Phủ, Thanh Khê",
    district: "Thanh Khê",
    lat: 16.071,
    lng: 108.193,
    price: 1800000,
    area: 18,
    room_type: "phong_tro",
    max_occupants: 1,
    gender_preference: "female",
    amenities: {
      wifi: true,
      ac: false,
      washer: false,
      parking: true,
      security: true,
      elevator: false,
      kitchen: false,
      balcony: false,
      pet: false,
    },
    status: "active",
    contact_phone: "0912345678",
    view_count: 89,
    contact_count: 7,
    created_at: "2026-05-22T14:00:00Z",
    images: [
      { id: "i6", listing_id: "3", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80", order: 0 },
    ],
    landlord: {
      user_id: "u3",
      full_name: "Lê Thị Lan",
      avatar_url: null,
      phone: "0912345678",
      verified_phone: true,
      verified_id: false,
    },
  },
  {
    id: "4",
    landlord_id: "u4",
    city: "da-nang",
    source: "admin",
    source_note: "Khảo sát thực địa khu Ngũ Hành Sơn, chủ nhà Phạm Minh Tuấn đã xác nhận qua Zalo",
    title: "Nhà nguyên căn 2PN khu dân cư Ngũ Hành Sơn",
    description:
      "Nhà nguyên căn 2 phòng ngủ, phù hợp gia đình hoặc nhóm bạn. Hẻm thông thoáng, yên tĩnh. Gần biển Non Nước 10 phút xe.",
    address: "32 Lê Văn Hiến, Ngũ Hành Sơn",
    district: "Ngũ Hành Sơn",
    lat: 16.002,
    lng: 108.265,
    price: 6000000,
    area: 60,
    room_type: "nha_nguyen_can",
    max_occupants: 4,
    gender_preference: "all",
    amenities: {
      wifi: true,
      ac: true,
      washer: true,
      parking: true,
      security: false,
      elevator: false,
      kitchen: true,
      balcony: true,
      pet: true,
    },
    status: "active",
    contact_phone: "0977654321",
    view_count: 64,
    contact_count: 5,
    created_at: "2026-05-21T09:00:00Z",
    images: [
      { id: "i7", listing_id: "4", url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80", order: 0 },
      { id: "i8", listing_id: "4", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80", order: 1 },
    ],
    landlord: {
      user_id: "u4",
      full_name: "Phạm Minh Tuấn",
      avatar_url: null,
      phone: "0977654321",
      verified_phone: true,
      verified_id: true,
    },
  },
  {
    id: "5",
    landlord_id: "u5",
    city: "da-nang",
    source: "landlord",
    title: "Phòng trọ Sơn Trà gần cầu Rồng, wifi tốc độ cao",
    description:
      "Phòng trọ mới renovate, view cầu Rồng cực đỉnh. Wifi 100Mbps, điều hoà inverter tiết kiệm điện. Thích hợp freelancer và người đi làm.",
    address: "15 Ngô Quyền, Sơn Trà",
    district: "Sơn Trà",
    lat: 16.061,
    lng: 108.237,
    price: 3200000,
    area: 28,
    room_type: "phong_tro",
    max_occupants: 2,
    gender_preference: "all",
    amenities: {
      wifi: true,
      ac: true,
      washer: false,
      parking: true,
      security: true,
      elevator: false,
      kitchen: true,
      balcony: true,
      pet: false,
    },
    status: "active",
    contact_phone: "0933211987",
    view_count: 143,
    contact_count: 18,
    created_at: "2026-05-19T11:00:00Z",
    images: [
      { id: "i9", listing_id: "5", url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80", order: 0 },
      { id: "i10", listing_id: "5", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80", order: 1 },
    ],
    landlord: {
      user_id: "u5",
      full_name: "Võ Quang Huy",
      avatar_url: null,
      phone: "0933211987",
      verified_phone: true,
      verified_id: true,
    },
  },
  {
    id: "6",
    landlord_id: "u1",
    city: "da-nang",
    source: "landlord",
    title: "Phòng trọ khép kín Liên Chiểu, gần KCN Hòa Khánh",
    description:
      "Phòng khép kín, WC riêng, máy nóng lạnh. Gần KCN Hòa Khánh, phù hợp công nhân/người đi làm. An ninh đảm bảo.",
    address: "200 Tôn Đức Thắng, Liên Chiểu",
    district: "Liên Chiểu",
    lat: 16.082,
    lng: 108.143,
    price: 2000000,
    area: 20,
    room_type: "phong_tro",
    max_occupants: 2,
    gender_preference: "all",
    amenities: {
      wifi: true,
      ac: true,
      washer: false,
      parking: true,
      security: true,
      elevator: false,
      kitchen: false,
      balcony: false,
      pet: false,
    },
    status: "active",
    contact_phone: "0905123456",
    view_count: 97,
    contact_count: 11,
    created_at: "2026-05-23T07:00:00Z",
    images: [
      { id: "i11", listing_id: "6", url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", order: 0 },
    ],
    landlord: {
      user_id: "u1",
      full_name: "Nguyễn Văn An",
      avatar_url: null,
      phone: "0905123456",
      verified_phone: true,
      verified_id: true,
    },
  },
];
